SELECT YEAR(SALES_DATE) AS YEAR
     , MONTH(SALES_DATE) AS MONTH
     , COUNT(DISTINCT o.USER_ID) AS PUCHASED_USERS
     , ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(*) 
                                    FROM USER_INFO 
                                    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'),1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS o
    LEFT JOIN USER_INFO AS u ON o.USER_ID = u.USER_ID
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
