-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
WHERE CAR_TYPE = '세단' AND C.CAR_ID IN (
    SELECT DISTINCT(CH.CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CH
    WHERE SUBSTR(START_DATE,6,2) = '10'
)
ORDER BY C.CAR_ID DESC

