-- 코드를 입력하세요

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON(I.ANIMAL_ID = O.ANIMAL_ID)
WHERE I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
ORDER BY I.ANIMAL_ID;
/*
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON(I.ANIMAL_ID = O.ANIMAL_ID)
WHERE I.SEX_UPON_INTAKE Like "Intact%" 
AND (O.SEX_UPON_OUTCOME Like "Spayed%" OR O.SEX_UPON_OUTCOME Like "Neutered%")
Order by I.Animal_id;
*/
