-- 코드를 입력하세요
# 조인 없이 실패. UGU에서 쓰는 Column 때문에 중복이 생김
# SELECT UGYU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
# FROM USED_GOODS_BOARD AS UGB, USED_GOODS_USER AS UGU
# WHERE UGB.STATUS = 'DONE'
# GROUP BY UGB.WRITER_ID
# HAVING SUM(UGB.PRICE) >= 700000
# ORDER BY SUM(UGB.PRICE)

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD INNER JOIN USED_GOODS_USER ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE)
