SELECT a.AUTHOR_ID
     , a.AUTHOR_NAME
     , b.CATEGORY
     , SUM((SALES * PRICE)) AS TOTAL_SALES
FROM BOOK b
INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
INNER JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE LIKE '2022-01%'
GROUP BY b.CATEGORY, b.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC
