SELECT b.USER_ID
     , b.NICKNAME
     , CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소'
     , CONCAT(SUBSTRING(b.TLNO,1,3),'-',SUBSTRING(b.TLNO,4,4),'-',(SUBSTRING(b.TLNO,8,4))) AS '전화번호'
FROM USED_GOODS_BOARD AS a
INNER JOIN USED_GOODS_USER AS b ON a.WRITER_ID = b.USER_ID
GROUP BY b.USER_ID
HAVING COUNT(a.WRITER_ID) >= 3
ORDER BY b.USER_ID DESC
