SELECT CONCAT('/home/grep/src/',f.BOARD_ID,'/',f.FILE_ID,f.FILE_NAME,f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_FILE f ON b.BOARD_ID =  f.BOARD_ID
WHERE b.views = (SELECT MAX(views) FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC
