SELECT PRODUCT_ID
     , YEAR AS FIRST_YEAR
     , QUANTITY
     , PRICE
FROM (SELECT PRODUCT_ID
           , YEAR
           , QUANTITY
           , PRICE
           , RANK() OVER(PARTITION BY PRODUCT_ID ORDER BY YEAR) AS RN
       FROM SALES) AS ranks 
WHERE RN = 1  
ORDER BY PRODUCT_ID
