-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE) 
                       FROM FOOD_PRODUCT
                       WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
                       GROUP BY CATEGORY)
ORDER BY PRICE DESC


# ERROR인 이유 GROUP화 할떄의 PRODUCT_NAME을 특정할 수 없어서
# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# GROUP BY CATEGORY
# ORDER BY PRICE DESC
