WITH MAX_REVIEW AS(
    SELECT COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW AS r
        LEFT JOIN MEMBER_PROFILE AS m ON r.MEMBER_ID = m.MEMBER_ID
    GROUP BY  r.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
), MAX_REVIEW_MEMBER_ID AS(
    SELECT r.MEMBER_ID
    FROM REST_REVIEW AS r
        LEFT JOIN MEMBER_PROFILE AS m ON r.MEMBER_ID = m.MEMBER_ID
    GROUP BY  r.MEMBER_ID
    HAVING COUNT(*) = (SELECT * FROM MAX_REVIEW)
)

SELECT MEMBER_NAME
     , REVIEW_TEXT
     , DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS r
    LEFT JOIN MEMBER_PROFILE AS m ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID IN (SELECT * FROM MAX_REVIEW_MEMBER_ID)
ORDER BY REVIEW_DATE, REVIEW_TEXT
