WITH RECURSIVE RC AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM RC
    WHERE HOUR <23
), A AS(
    SELECT HOUR(DATETIME) AS HOUR
         , COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR
)

SELECT RC.HOUR
     , CASE 
        WHEN COUNT IS NULL THEN 0
        ELSE COUNT
       END AS COUNT 
FROM RC
    LEFT JOIN A ON RC.HOUR = A.HOUR
